<?php /** @var Ho_PriceCrawler_Block_Adminhtml_Dashboard_Schedule $this */ ?>
<?php /** @var Ho_PriceCrawler_Helper_Data $helper */ ?>
<?php $helper = Mage::helper('ho_pricecrawler'); ?>
<?php $spiders = $this->getSpidersWithJobInfo(); ?>
<table cellspacing="0" style="border:0;" id="schedule_jobs_table">
    <colgroup>
        <col>
        <col width="100">
        <col width="100">
        <col width="100">
    </colgroup>
    <thead>
    <tr class="headings">
        <th class="no-link"><?=$this->__('Spider');?></th>
        <th class="no-link"><?=$this->__('To be imported');?></th>
        <th class="no-link" colspan="2" style="text-align: right;"><?=$this->__('Actions');?></th>
    </tr>
    </thead>
    <?php if (count($spiders)): ?>
        <?php /** @var Ho_PriceCrawler_Model_Sites $spider */ ?>
        <?php foreach ($spiders as $spider): ?>
            <?php $job = $spider->getJob() ? $spider->getJob() : false; ?>
            <tr>
                <td><?php echo $spider->getName(); ?></td>
                <td><?=$job ? $job->items_scraped : '-'; ?></td>
                <td style="text-align: right;">
                    <?php if ($job->items_scraped): ?>
                    <a href="<?=Mage::getUrl('ho_pricecrawler/adminhtml_dashboard/import', array('spider' => $spider->getIdentifier())); ?>">
                        <button><?=$this->__('Import items now');?></button>
                    </a>
                    <?php endif; ?>
                </td>
                <td style="text-align: right;">
                    <?php if ($job->items_scraped): ?>
                        <?php if ($this->hasLogs($job->id)): ?>
                            <a href="<?=Mage::getUrl('ho_pricecrawler/adminhtml_dashboard/importlogs',
                                array('spider' => $spider->getIdentifier(), 'job' => base64_encode($job->id))); ?>">
                                <button><?=$this->__('Import logs now');?></button>
                            </a>
                        <?php else: ?>
                            <a href="<?=$helper->getLogsGridUrl($job->id);?>"
                               data-tooltip="<?=$this->__('Show logs of this job');?>" class="tooltip tooltip-nowrap">
                                <?=$this->__('Show logs of this job');?>
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="2" style="color:#999;"><?=$this->__('No spiders found'); ?></td>
        </tr>
    <?php endif; ?>
</table>